#ifndef __RT_AI_MNIST_MODEL_H
#define __RT_AI_MNIST_MODEL_H

#include <mnist.h>
#include <mnist_data.h>

/* model info ... */

// model name
#define RT_AI_MNIST_MODEL_NAME			"mnist"
#define RT_AI_MNIST_WORK_BUFFER_BYTES		AI_MNIST_DATA_ACTIVATIONS_SIZE
#define RT_AI_MNIST_DATA_WEIGHTS_SIZE		AI_MNIST_DATA_WEIGHTS_SIZE

#define RT_AI_MNIST_BUFFER_ALIGNMENT		AI_MNIST_ACTIVATIONS_ALIGNMENT

#define RT_AI_MNIST_IN_NUM				AI_MNIST_IN_NUM
#define RT_AI_MNIST_IN_1_SIZE				AI_MNIST_IN_1_SIZE
#define RT_AI_MNIST_IN_1_SIZE_BYTES		AI_MNIST_IN_1_SIZE_BYTES
#define RT_AI_MNIST_IN_TOTAL_SIZE_BYTES	(AI_MNIST_IN_1_SIZE_BYTES)
#define RT_AI_MNIST_IN_SIZE_BYTES			{AI_MNIST_IN_1_SIZE_BYTES}


#define RT_AI_MNIST_OUT_NUM				AI_MNIST_OUT_NUM
#define RT_AI_MNIST_OUT_1_SIZE			AI_MNIST_OUT_1_SIZE
#define RT_AI_MNIST_OUT_1_SIZE_BYTES		AI_MNIST_OUT_1_SIZE_BYTES
#define RT_AI_MNIST_OUT_TOTAL_SIZE_BYTES	(AI_MNIST_OUT_1_SIZE_BYTES)
#define RT_AI_MNIST_OUT_SIZE_BYTES		{AI_MNIST_OUT_1_SIZE_BYTES}


#define RT_AI_MNIST_TOTAL_BUFFER_SIZE		(NULL)		//unused

#endif	//end
